on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Build and test
        run: make build test

      - name: Deploy
        run: ./deploy.sh
